version: 2
updates:
  # Update GitHub actions
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
    labels:
      - dependencies

  # Update Docker base images
  - directory: /
    package-ecosystem: docker
    schedule:
      interval: daily
    commit-message:
      prefix: build(docker)
    labels:
      - dependencies