name: Poll branch releases
on:
  workflow_call:
    inputs:
      branch:
        description: 'App branch'
        type: string
        default: 'master'

    outputs:
      updateRequired:
        description: 'New version found'
        value: ${{ jobs.check-upstream.outputs.update }}
      upstreamVersion:
        description: 'Upstream version'
        value: '${{ jobs.check-upstream.outputs.version }}'

jobs:
  check-upstream:
    name: Check upstream version
    runs-on: ubuntu-latest

    env:
      currentVersion: ${{ vars.RELEASE_VERSION }}

    permissions:
      contents: write

    strategy:
      fail-fast: true
      matrix:
        arch: ["amd64"]
        include:
          - arch: amd64
            os: ubuntu-latest

    outputs:
      update: ${{ steps.check_tag.outputs.exists == 'false' }}
      version: '${{ steps.upstream.outputs.version }}'

    steps:
    - name: Get upstream version
      id: upstream
      run: |
        VERSION=$(curl -sL --request GET \
          --url "https://hub.docker.com/v2/repositories/library/nextcloud/tags/?page_size=1000" \
          | jq -r '.results | .[] | select(.name | contains("-") | not) | .name' \
          | sed -r '/(latest|stable|production|fpm|apache)/d' \
          | sort --version-sort \
          | tail -n 1)
        
        echo "version=${TAG//v}" >> $GITHUB_OUTPUT

    - name: Check if tag exists
      uses: mukunku/tag-exists-action@v1.6.0
      id: check_tag
      with:
        tag: 'v${{ steps.upstream.outputs.version }}'

    - uses: actions/checkout@v4
      if: steps.check_tag.outputs.exists == 'false'

    - name: Update Readme
      uses: jacobtomlinson/gha-find-replace@v3
      if: steps.check_tag.outputs.exists == 'false'
      with:
        find: '${{ env.currentVersion }}'
        replace: '${{ steps.upstream.outputs.version }}'
        include: 'README.md'
        regex: false

    - name: Push changes
      uses: EndBug/add-and-commit@v9
      if: steps.check_tag.outputs.exists == 'false'
      with:
        committer_name: GitHub Actions
        committer_email: actions@github.com
        message: 'docs: Bump image version to ${{ steps.upstream.outputs.version }}'
        tag: 'v${{ steps.upstream.outputs.version }}'