name: New release check
on:
  push:

  # Hourly
  schedule:
    - cron:  '0 0 * * *'

  # Manually
  workflow_dispatch:

jobs:
  masterPoll:
    name: 'Poll master branch'
    uses: ./.github/workflows/poll_releases.yml

  masterBuild:
    name: 'Build master branch'
    uses:  ./.github/workflows/build_release.yml
    if: ${{ needs.masterPoll.outputs.updateRequired == 'true' }}
    needs: 
    - masterPoll
    with:
      upstreamVersion: '${{ needs.masterPoll.outputs.upstreamVersion }}'